version: '1.0'

services:
  backend:
    container_name: book-crud-backend
    build: .
    ports:
      - "8080:8080"
    restart: "always"

  mongo:
    image: mongo
    volumes:
      - "./data:/data/db"
    ports:
      - "27017:27017"
